<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\YaMiSoFt.OpenData.Core\YaMiSoFt.OpenData.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="5.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
